# .kodiak.toml
# Minimal config. version is the only required field.
version = 1

merge.require_automerge_label = false
merge.method = "squash"

[approve]
approve.auto_approve_usernames = ["kodiakhq"]

[merge.automerge_dependencies]
# only auto merge "minor" and "patch" and "major" version upgrades.
versions = ["minor", "patch", "major"]
usernames = ["torbacz"]
